import random as rand

Mots = 'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z AA AH AI AN AS AU AY BA BE BI BU CA CE CI DA DE DO DU EH EN ES ET EU EX FA FI GO HA HE HI HO IF IL IN JE KA LA LE LI LU MA ME MI MU NA NE NI NO NU OC OH OM ON OR OS OU PI PU QI RA RE RI RU SA SE SI SU TA TE TO TU UD UN US UT VA VE VS VU WU XI AAS ACE ADA ADO AGA AGE AGI AID AIE AIL AIR AIS AIT ALE ALU AME AMI ANA ANE ANI ANS API APP ARA ARC ARE ARF ARS ART ASA ASE AUX AVE AXA AXE AYS BAC BAH BAI BAL BAN BAO BAR BAS BAT BAU BEA BEC BEE BEL BEN BER BEU BEY BIB BIC BIM BIO BIP BIS BIT BLE BOA BOB BOF BOG BOL BON BOP BOT BOX BOY BRU BUE BUG BUN BUS BUT BYE CAB CAF CAL CAP CAR CAS CEP CES CET CHU CIF CIL CIS CLE COB COI COL COM CON COQ COR COT COU COX CRE CRI CRU CUL CUT DAB DAH DAL DAM DAN DAO DAW DEB DEJ DEL DEM DEO DER DES DEY DIA DIN DIP DIS DIT DIX DOC DOL DOM DON DOP DOS DOT DRU DRY DUB DUC DUE DUO DUR DUS DUT DYS DZO EAU ECO ECU EGO ELU EMU EON EPI ERE ERG ERS EST ETA ETE EUE EUH EUS EUT EUX EVE EWE EXO FAC FAF FAN FAQ FAR FAT FAX FEE FER FEU FEZ FIA FIC FIE FIL FIN FIS FIT FIU FIX FLA FOB FOC FOG FOI FOL FON FOR FOU FOX FUI FUN FUR FUS FUT GAG GAI GAL GAN GAP GAY GAZ GEL GEO GEX GHI GIF GIN GIS GIT GLU GOI GON GOS GOY GRE GUE GUI GUR GUS GYM HAI HAN HEM HEP HEU HIA HIC HIE HIP HIT HOP HOT HOU HUA HUB HUE HUI HUM HUN IBN IBO ICI IDE IEL IFS ILE ILS ION IPE IRA IRE ISO IVE IXA IXE JAB JAM JAN JAR JAS JET JEU JOB JUS KAN KAS KAT KEA KEN KET KHI KID KIF KIL KIP KIR KIT KOB KOI KOP KOT KRU KSI KWA KYU LAC LAD LAI LAO LAS LED LEI LEK LEM LES LET LEU LEV LEZ LIA LIE LIN LIS LIT LOA LOB LOF LOG LOI LOL LOS LOT LUE LUI LUO LUS LUT LUX LYS MAC MAG MAI MAL MAN MAO MAS MAT MAX MEC MEL MEO MER MES MET MIE MIL MIN MIR MIS MIT MIX MMM MOA MOB MOI MOL MON MOR MOS MOT MOU MOX MUA MUE MUG MUR MUS MUT MYE NAC NAN NAY NEE NEF NEM NEO NES NET NEY NEZ NIA NIB NID NIE NIF NIM NIT NOM NON NOS NUA NUE NUI NUL NUS OBA OBI ODE OFF OHE OHM OIE OIL OIS OIT OKA OLA OLE ONC ONT OPE ORE ORS OSA OSE OST OTA OTE OUD OUF OUH OUI OUT OVE OXO OYE PAF PAL PAN PAP PAR PAS PAT PEC PEP PET PEU PFF PHI PHO PIC PIE PIF PIN PIS PIU PLI PLU POP POT POU PRE PRO PSI PST PSY PUA PUB PUE PUR PUS PUT PUY QAT QIN QIS QUE QUI RAB RAC RAD RAI RAM RAP RAS RAT RAY RAZ REA REE REG REM REZ RHE RHO RIA RIB RIE RIF RIO RIS RIT RIZ ROB ROC ROI ROM ROS ROT RUA RUE RUS RUT RUZ RYE SAC SAI SAL SAR SAS SAX SEC SEL SEN SEP SES SET SIC SIL SIR SIS SIX SKA SKI SOC SOI SOL SOM SON SOT SOU SPA SPI SUA SUC SUD SUE SUP SUR SUS SUT TAC TAF TAG TAN TAO TAR TAS TAT TAU TEC TEE TEF TEK TEL TEP TER TES TET TEX THE TIC TIF TIN TIP TIR TOC TOF TOI TOM TON TOP TOS TOT TRI TUA TUB TUE TUF TUS TUT UDS UNE UNI UNS URE USA USE UTE VAL VAN VAR VAS VAT VAU VER VES VET VIA VIE VIF VIL VIN VIS VIT VOC VOL VOS VUE VUS WAD WAP WAX WEB WOH WOK WON WUS XIS YAK YAM YEN YET YIN YOD YUE ZEC ZEE ZEF ZEK ZEN ZIG ZIP ZOB ZOE ZOO ZOU ZUP ZUT ABAT ABBE ABDO ABEE ABER ABLE ABOI ABOT ABRI ABUS ACAI ACCU ACES ACHE ACME ACNE ACON ACRA ACRE ACTA ACTE ACTU ACUL ADAC ADAS ADAV ADNE ADON ADOS AEDE AERA AERE AFAR AFAT AFIN AFRO AGAS AGEE AGES AGHA AGIE AGIO AGIR AGIS AGIT AGNI AGUI AHAN AIDA AIDE AIDS AIES AIGU AILE AILS AIMA AIME AINE AIRA AIRE AIRS AISE AISY AJUT AKAN ALEA ALEM ALES ALFA ALLA ALLE ALLO ALOI ALPA ALPE ALTI ALTO ALUN ALUS ALYA AMAN AMAS AMEN AMER AMES AMIE AMIS AMMI AMOK AMUI ANAL ANAR ANAS ANEE ANEL ANES ANGE ANIL ANIS ANKH ANON ANSE ANTE ANUS AOUT APAX APEX APIS APPS APRE APTE ARAC ARAK ARAS ARCH ARCS ARDU AREC AREG ARES AREU ARGH ARIA ARMA ARME AROL ARTS ARTY ARUM ASES ASIC ASIN ASPE ASPI ASSE ASSO ASTE ASTI ATRE AUBE AUGE AULA AULX AUNA AUNE AURA AUTO AVAL AVEC AVEN AVES AVEU AVEZ AVIS AXAI AXAS AXAT AXEE AXEL AXER AXES AXEZ AXIS AXOA AYEZ AZUR BABA BABY BACS BADA BADE BAES BAHT BAIE BAIL BAIN BAIS BALE BALS BANC BANG BANI BANS BAOS BAOU BARD BARN BARS BASA BASE BASI BATA BATE BATH BATI BATS BAUD BAUX BAVA BAVE BAYA BAYE BEAI BEAS BEAT BEAU BEBE BECS BEDE BEER BEES BEEZ BEGU BEKE BELA BELE BELS BENE BENI BENS BERK BERS BETA BETE BETI BEUH BEUR BEUS BEYS BIBI BIBS BICS BIDE BIEF BIEN BIGE BIGO BILA BILE BILL BINA BINE BING BINZ BIOS BIPA BIPE BIPS BIRR BISA BISE BITA BITE BITS BITU BIWA BLED BLES BLET BLEU BLOB BLOC BLOG BLOT BOAS BOBO BOBS BOCK BODY BOER BOGE BOGS BOIS BOIT BOLO BOLS BOME BOND BONI BONS BOOK BOOM BOOT BOPS BORA BORD BORE BORT BOSS BOTE BOTO BOTS BOUC BOUE BOUH BOUM BOUR BOUS BOUT BOXA BOXE BOYS BRAI BRAN BRAS BREF BREN BRIC BRIE BRIK BRIN BRIO BRIS BROC BROL BROU BRRR BRUI BRUN BRUS BRUT BUEE BUES BUGS BUIS BULB BULL BUNA BUNS BURE BURG BUSA BUSC BUSE BUSH BUTA BUTE BUTO BUTS BUZZ BYTE CABS CACA CADE CADI CAFE CAGE CAID CAKE CALA CALE CALF CALL CALO CALS CAMA CAME CAMP CANA CANE CANT CAPA CAPE CAPO CAPS CARI CARS CARY CASA CASE CASH CATA CATE CATI CAVA CAVE CAYE CEBE CECI CEDA CEDE CEDI CELA CELE CENE CENS CENT CEPE CEPS CERF CERS CEUX CHAH CHAI CHAN CHAR CHAS CHAT CHEB CHEF CHER CHEZ CHIA CHIC CHIE CHIP CHOC CHOP CHOU CHTI CHUE CHUM CHUS CHUT CHVA CIAO CIEL CILS CIME CINE CINQ CIRA CIRE CITA CITE CIVE CLAC CLAM CLAN CLAP CLAY CLEF CLES CLIC CLIM CLIN CLIP CLOS CLOT CLOU CLUB CLUE COBE COBS COCA COCO COCU CODA CODE COEF COIN COIR COIS COIT COKE COLA COLO COLS COLT COMA COMS CONE CONS COOL COPS COQS CORB CORE CORS COSY COTA COTE COTI COTS COUD COUP COUR COUS COUT COUV COXA COXE CRAC CRAN CRAU CREA CREE CRET CRIA CRIB CRIC CRIE CRIN CRIS CROC CROW CRUE CRUS CRUT CUBA CUBE CUBI CUCU CUIR CUIS CUIT CULA CULE CULS CURA CURE CUTI CUTS CUVA CUVE CYAN CYME CYON CZAR DABA DABE DABS DACE DADA DAHL DAHS DAHU DAIL DAIM DAIS DALS DAMA DAME DAMS DANS DAOS DARD DARI DATA DATE DAUW DAWS DEAL DEBS DECA DECI DECK DECO DECU DEFI DEJA DEJS DELA DELS DEME DEMI DEMO DEMS DENI DENT DEOS DERS DESK DEUG DEUX DEVI DEYS DHAL DIAL DIAM DIAS DIBI DICO DIEU DIME DINA DINE DING DIOL DIOT DIPS DIRA DIRE DISE DITE DITO DITS DIVA DIVE DOCK DOCS DOCU DODO DODU DOGE DOIS DOIT DOJO DOLA DOLE DOLO DOLS DOME DOMS DONA DONC DONF DONG DONS DONT DOPA DOPE DOPS DORA DORE DORS DORT DOSA DOSE DOTA DOTE DOTS DOUA DOUC DOUE DOUF DOUM DOUX DOXA DRAG DRAM DRAP DROP DRUE DRUS DRYS DUAL DUBS DUCE DUCS DUEL DUES DUIT DUNE DUNK DUOS DUPA DUPE DURA DURE DURS DUSE DYKE DYNE DZOS EAUX EBAT ECHA ECHE ECHO ECHU ECOS ECOT ECRU ECUS EDAM EDEN EDIT EGAL EGOS EJET ELAN ELFE ELIA ELIE ELIS ELIT ELLE ELUA ELUE ELUS ELUT EMBU EMET EMEU EMIA EMIE EMIR EMIS EMIT EMOI EMOU EMUE EMUS EMUT ENOL ENTA ENTE ENVI EONS EPAR EPEE EPIA EPIE EPIS EPOI ERES ERGS EROS ERRA ERRE ERSE ESSE ESTE ETAI ETAL ETAS ETAT ETAU ETES ETOC ETRE ETUI EUES EURO EVES EVOE EWEE EWES EXAM EXIL EXIT EXON EXOS EXPO EYRA FACE FACS FADA FADE FADO FAFS FAIM FAIS FAIT FAIX FAKE FAME FANA FANE FANG FANS FAON FAQS FARD FARE FARO FARS FART FATE FATS FAUT FAUX FAXA FAXE FEAL FEAT FEDE FEES FELA FELE FEND FERA FERS FERU FETA FETE FETU FEUE FEUJ FEUS FEUX FEVE FIAI FIAS FIAT FICS FIEE FIEF FIEL FIER FIES FIEU FIEZ FIFI FIGE FILA FILE FILM FILO FILS FINE FINI FINN FINS FION FIQH FISC FITS FIUS FIXA FIXE FIZZ FLAC FLAG FLAN FLAT FLET FLIC FLIP FLOC FLOE FLOP FLOT FLOU FLOW FLUA FLUE FLUO FLUX FOCS FOGS FOHN FOIE FOIL FOIN FOIS FOLK FOND FONS FONT FOOT FORA FORE FORS FORT FOUI FOUR FOUS FOUT FOXE FRAC FRAI FRET FRIC FRIS FRIT FROC FUEL FUGU FUIE FUIR FUIS FUIT FULL FUMA FUME FUNE FUNK FUNS FUSA FUSE FUTE FUTS GABA GADE GAGA GAGE GAGS GAIE GAIN GAIS GALA GALE GALS GANG GANS GANT GAPS GARA GARE GARI GARS GASP GATA GATE GAUR GAVA GAVE GAYS GAZA GAZE GEAI GEEK GELA GELE GELS GEMI GENA GENE GENS GENT GEOS GERA GERE GHEE GHIS GIFS GIFT GIGA GINS GIRL GITA GITE GLAM GLAS GLEY GLIE GLUA GLUE GLUI GLUS GNON GNOU GOAL GOBA GOBE GODA GODE GOGE GOGO GOIM GOIS GOJI GOLF GOND GONE GONG GONS GORD GORE GOTH GOUM GOUR GOUT GOYA GOYM GOYS GRAF GRAM GRAS GRAU GRAY GREA GREC GREE GRES GRIL GRIP GRIS GROG GROS GRRR GRUE GUAI GUAR GUEA GUEE GUES GUET GUIB GUIS GUNZ GURS GURU GUSS GYMS GYRE HACH HADJ HAIE HAIK HAIR HAIS HAIT HAJE HAKA HALA HALE HALL HALO HAND HANS HARD HARO HART HASE HAST HATA HATE HAUT HAVA HAVE HAVI HEIN HELA HELE HEME HERE HERO HEUR HIAI HIAS HIAT HICS HIEE HIER HIES HIEZ HIFI HILE HIPS HITS HOAX HOCA HOIR HOKI HOLA HOME HOMO HOPI HORA HORS HOST HOTE HOTS HOTU HOUA HOUE HOUP HOUX HOVA HUAI HUAS HUAT HUBS HUEE HUER HUES HUEZ HUIS HUIT HUMA HUME HUNE HUNS HURE HUTU HYPE IBIS IBNS IBOS IDEE IDEM IDES IELS IGBO IGNE IGUE IKAT ILES ILET ILOT IMAM IMAN IMBU INCA INCH INDE INDU INFO INIE INNE INNU INOX INSU INTI INUK IODA IODE IONS IOTA IPES IRAI IRAS IRES IREZ IRIS ISBA ISME ISSA ISSU ITEM ITOU IULE IVES IVRE IWAN IXAI IXAS IXAT IXEE IXER IXES IXEZ IXIA JABS JACK JACO JADE JAIN JAIS JAJA JALE JAMS JANS JARD JARS JASA JASE JASS JATI JAVA JAZZ JEAN JEEP JERK JESE JETA JETE JETS JEUN JEUX JEZE JIVE JOBA JOBE JOBS JOIE JOJO JOLI JONC JOTA JOUA JOUE JOUG JOUI JOUR JUBE JUDD JUDO JUGE JUIF JUIN JUMP JUNK JUPE JURA JURE JURY JUTA JUTE KADI KAKI KALE KALI KAMI KANA KANS KAON KAPO KART KATA KATS KAVA KAWA KAWI KEAS KEKE KELP KENA KENS KEPI KERN KETS KEUF KEUM KHAN KHAT KHIS KHOL KICK KIDS KIEF KIFA KIFE KIFF KIFS KIKI KILO KILS KILT KINA KINE KIPS KIRS KITE KITS KIVA KIWI KOAN KOBS KOIS KOKA KOLA KOPS KORA KORE KOTA KOTE KOTO KOTS KRAK KRUS KSAR KSIS KUNA KURU KVAS KWAS KYAT KYUS LABO LACA LACE LACK LACS LADS LADY LAIC LAID LAIE LAIS LAIT LAKH LALA LAMA LAMB LAME LAND LAOS LAPA LAPE LAPS LARD LARE LARI LATS LAVA LAVE LAYA LAYE LAZE LEDS LEGE LEGO LEGS LEHM LEKS LEMS LENT LESA LESE LEST LEUR LEUS LEVA LEVE LEVS LIAI LIAS LIAT LICE LIDO LIED LIEE LIEN LIER LIES LIEU LIEZ LIFT LIGE LIKA LIKE LIMA LIME LINO LINS LION LIRA LIRE LISE LISP LITA LITE LITS LIVE LOAS LOBA LOBE LOBI LOBS LOCH LOCI LOCO LODS LOFA LOFE LOFS LOFT LOGE LOGO LOGS LOIN LOIR LOIS LOLO LOMO LONE LONG LOOK LORD LORI LORS LOSE LOTE LOTI LOTO LOTS LOUA LOUE LOUF LOUP LOVA LOVE LUES LUGE LUIS LUIT LULU LUMA LUMP LUNE LUOS LUTA LUTE LUTH LUTS LUTZ LUXA LUXE LYNX LYRA LYRE LYSA LYSE MAAR MACH MACS MAFE MAGE MAGS MAIA MAIE MAIL MAIN MAIS MAJE MAKI MAKO MALE MALI MALM MALS MALT MAMA MAME MAMY MANA MANS MANX MAOS MARA MARC MARE MARI MARK MARS MASO MATA MATE MATH MATI MATS MATU MAUL MAUX MAXI MAYA MAYE MAYO MAZA MAZE MEAT MECS MEDE MEGA MEGI MELA MELE MELO MELS MEME MEMO MENA MENE MENS MENT MENU MEOS MERE MERL MERS MESA MESS META METS MEUF MEUH MEUS MEUT MEZE MIAM MICA MIDI MIEL MIEN MIES MILE MILS MIMA MIME MIMI MINA MINE MING MINI MINS MIPS MIRA MIRE MIRO MIRS MISA MISE MISO MISS MITA MITE MIXA MIXE MOAI MOAS MOBS MOCO MODE MOHO MOIE MOIS MOJO MOKA MOKO MOLE MOLY MOME MONO MONS MONT MOOC MOOK MORD MORE MORS MORT MOTO MOTS MOUD MOUE MOUS MOUT MOXA MOYA MOYE MUAI MUAS MUAT MUEE MUER MUES MUET MUEZ MUGE MUGI MUGS MUID MULE MULL MUNI MUON MURA MURE MURI MURS MUSA MUSC MUSE MUST MUTA MUTE MYES NAAN NABI NACS NADA NAFE NAGA NAGE NAGI NAIF NAIN NAIS NAIT NAJA NANA NANS NANT NAOS NARD NASE NAVE NAYS NAZE NAZI NECK NEEM NEES NEFS NEGO NELL NEMI NEMS NENE NEON NEOS NEPE NERD NERE NERF NETS NEUF NEVE NEWS NEYS NIAI NIAS NIAT NIDA NIDS NIEE NIER NIES NIET NIEZ NIFE NIFS NIMS NITS NIVE NIXE NOCA NOCE NOEL NOIE NOIR NOIX NOMA NOME NOMS NONE NONO NORD NORI NOTA NOTE NOUA NOUC NOUE NOUS NOVA NOVE NOVI NOVO NOYA NOYE NUAI NUAS NUAT NUBA NUEE NUER NUES NUEZ NUIS NUIT NULS OBAS OBEI OBEL OBIS OBIT OBUS OCRA OCRE OCTA ODES OEIL OEUF OFFS OGAM OGRE OHMS OIES OING OINS OINT OKAS OKRA OLAS OLIM OLLE OMET OMIS OMIT OMRA ONCE ONDE ONYX ONZE OPEN OPES OPEX OPTA OPTE OPUS ORAL ORBE ORDI ORDO OREE ORES ORGE ORIN ORLE ORME ORNA ORNE ORYX OSAI OSAS OSAT OSEE OSER OSES OSEZ OSSU OSTO OSTS OTAI OTAS OTAT OTEE OTER OTES OTEZ OUAF OUAH OUCH OUDS OUED OUFS OUIE OUIN OUIR OUIS OUIT OUPS OURS OUST OUZO OVEE OVES OVIN OVNI OXER OYAT OYES OYEZ PACA PACK PACS PAFS PAGE PAGI PAIE PAIN PAIR PAIS PAIT PAIX PALA PALE PALI PALS PALU PAMA PAME PANA PANE PANS PAON PAPA PAPE PAPI PAPY PARA PARC PARE PARI PARS PART PARU PASS PATE PATI PATS PAVA PAVE PAYA PAYE PAYS PEAN PEAU PECS PECU PELA PELE PEND PENE PENO PEON PEPE PEPS PERD PERE PERF PERI PERM PERS PESA PESE PESO PETA PETE PETS PEUF PEUH PEUL PEUR PEUT PEUX PEVE PEZE PFFT PFUT PHIS PHOS PHOT PIAF PIAN PICA PICS PIED PIER PIES PIEU PIFA PIFE PIFS PIGE PIKA PILA PILE PILS PINE PINS PION PIPA PIPE PIPI PIPO PIRE PISE PITA PITE PIVE PLAF PLAN PLAT PLIA PLIE PLIS PLOC PLOT PLUG PLUS PLUT PNEU POCO POGO POIL POIS POIX POKE POLE POLI POLO POLY POND PONT POOL POPE POPS PORC PORE PORT POSA POSE POST POTA POTE POTS POTU POUF POUH POUM POUR POUX POYA PRAO PRES PRET PRIA PRIE PRIS PRIT PRIX PROC PROD PROF PROS PROU PSIS PSST PSYS PUAI PUAS PUAT PUBS PUCA PUCE PUCK PUDU PUEE PUER PUES PUEZ PUIS PUJA PULA PULL PUMA PUNA PUNI PUNK PUNT PUNU PUPE PURE PURO PURS PUTE PUTS PUTT PUYS QATS QING QINS QUAD QUAI QUEL QUIA QUID QUIZ QUOI RAAG RABE RABS RACA RACE RACK RADA RADE RADS RAFT RAGA RAGE RAIA RAID RAIE RAIL RAIS RAIT RAJA RAKI RAKU RALA RALE RAMA RAME RAMI RAND RANG RANI RANZ RAPA RAPE RAPS RAPT RARE RASA RASE RASH RATA RATE RATS RAVE RAVI RAYA RAYE RAYS REAC REAI REAL REAS REAT REBU RECK RECU REDU REEL REER REES REEZ REGI REGS REIN REIS RELU REMS REND RENE REPS REPU RESA RETS REVA REVE REVU RHES RHOS RHUM RIAD RIAL RIAS RIBS RIDA RIDE RIEL RIEN RIES RIEZ RIFF RIFS RIFT RIMA RIME RING RIOS RIPA RIPE RIRA RIRE RISS RITE RITS RIVA RIVE RIXE ROBA ROBE ROBS ROCK ROCS RODA RODE ROIS ROKH ROLE ROMS ROND ROOF ROSA ROSE ROSI ROTA ROTE ROTI ROTO ROTS ROUA ROUE ROUF ROUI ROUX RUAI RUAS RUAT RUCK RUDE RUEE RUER RUES RUEZ RUGI RUMB RUNE RUPA RUPE RUSA RUSE RUSH RUTS RYAD RYAL RYES SACS SACY SADO SAGA SAGE SAIE SAIN SAIS SAIT SAKE SAKI SALA SALE SALI SALS SAME SAMI SAMU SANA SANG SANS SAPA SAPE SARA SARI SARS SART SATE SATI SAUF SAUR SAUT SAXE SAXO SCAN SCAT SCIA SCIE SCUD SEAU SECS SECU SEGA SEIN SELF SELS SEMA SEME SEMI SENE SENS SENT SEPS SEPT SERA SERE SERF SERS SERT SETS SEUL SEUM SEVE SEVI SEXA SEXE SEXY SHAH SHAN SHED SHIT SHOT SHOW SIAL SIDA SIDI SIED SIEE SIEN SIKA SIKH SILA SILE SILO SILS SILT SIMA SIPO SIRE SIRS SISE SITE SITU SIUM SKAI SKAS SKAT SKIA SKIE SKIF SKIN SKIP SKIS SKUA SKYR SLAM SLIM SLIP SLOW SLUM SMIC SMOG SMOK SNIF SNOB SOAP SOBA SOCS SODA SODE SOFA SOFT SOIE SOIF SOIN SOIR SOIS SOIT SOJA SOLE SOLI SOLO SOLS SOMA SOMS SONE SONG SONO SONS SONT SORE SORS SORT SOTS SOUE SOUK SOUL SOUM SOUS SOYA SPAM SPAS SPAT SPET SPIC SPIN SPIS SPOT SRAS STAR STAT STEM STEP STOP STOT STUC STUD STUP SUAI SUAS SUAT SUBI SUCA SUCE SUCS SUEE SUER SUES SUET SUEZ SUFI SUIE SUIF SUIS SUIT SUMO SUPA SUPE SURE SURF SURI SURS SWAG SWAP SWIN SYLI TAAL TACK TACO TACS TACT TAEL TAFS TAGS TAHR TAIE TAIN TAIS TAIT TAKA TALA TALC TALE TAMA TANG TANK TANN TANS TANT TAON TAOS TAPA TAPE TAPI TARA TARD TARE TARI TARO TARS TATA TATE TATI TATS TAUD TAUS TAUX TAXA TAXE TAXI TCHO TEAM TECH TECK TEES TEFF TEFS TEJU TEKE TEKS TELE TELL TELS TEND TENU TEST TETA TETE TETS TETU TEUF TEVE THAI THES THON THUG THYM TIAN TICS TIEN TIFO TIFS TIGE TIKI TILT TINE TINS TINT TIPA TIPE TIPI TIPS TIRA TIRE TIRS TISA TISE TITI TOBY TOCS TOFS TOFU TOGE TOIT TOLA TOLE TOLU TOMA TOME TOMS TOND TONG TONS TOPA TOPE TOPO TOPS TORD TORE TORR TORS TORT TORY TOSA TOSS TOTO TOUA TOUE TOUR TOUS TOUT TOUX TRAC TRAM TRAX TREK TRES TRIA TRIC TRIE TRIN TRIO TRIP TRIS TROC TROP TROT TROU TROY TRUC TSAR TUAI TUAS TUAT TUBA TUBE TUBS TUEE TUER TUES TUEZ TUFS TUNA TUNE TUPI TURC TURF TUTE TUTO TUTU TWIN TYPA TYPE TYPO TZAR UBAC UDON UGNI ULNA ULVE UMBO UMMA UNAU UNES UNIE UNIF UNIR UNIS UNIT UNIV UPAS URDU UREE URES URGE URNE URUS USAI USAS USAT USEE USER USES USEZ USUS UTES UVAL UVEE VAGI VAIN VAIR VAIS VALS VALU VAMP VANS VAPE VAPO VARA VARS VASA VASE VATU VAUT VAUX VEAU VECU VEDA VELA VELD VELE VELO VELU VEND VENE VENT VENU VERS VERT VETE VETO VETS VETU VEUF VEUT VEUX VEXA VEXE VIBE VICE VIDA VIDE VIES VIET VIFS VILE VILS VINA VINE VINS VINT VIOC VIOL VIRA VIRE VISA VISE VISU VITE VITS VIVE VIVO VLAN VLOG VOCS VOEU VOIE VOIR VOIS VOIT VOIX VOLA VOLE VOLS VOLT VOMI VONT VOTA VOTE VOUA VOUE VOUS VRAC VRAI VUES WADS WALE WALI WAPS WAQF WASP WATT WEBS WECH WESH WHIG WHIP WIFI WIKI WITZ WOKE WOKS WONS WRAP WURM YACK YAKA YAKS YAMS YANG YARD YASS YAWL YENS YETI YETS YEUX YEYE YINS YODS YOGA YOGI YOLE YORK YOUP YOYO YUAN YUES YUKO YUZU ZAIN ZAMU ZANI ZARB ZEBU ZECS ZEES ZEFS ZEKS ZELE ZEND ZENS ZERO ZEST ZETA ZIGS ZIKR ZINC ZIPS ZIRE ZIST ZIZI ZOBS ZOES ZONA ZONE ZOOM ZOOS ZOUK ZOZO ZUPS '

Pioche = 'AAAABCDDEEEEEEEEFGHIIIIJKLLLMMNNNOOOPQRRRSSSTTTUUVWXYZ'

Alpha ='ABCDEFGHIJKLMNOPQRSTUVWXYZ'

Points = '13321424189121138111149999'

def tirage(pioche: str, k: int) -> tuple[str, str]:
    if k >= len(pioche):
        return pioche, ""
    tired = ""
    for i in range(k):
        r = rand.randint(0, len(pioche)-1)
        tired += pioche[r]
        pioche = pioche[:r] + pioche[r+1:]
    return tired, pioche

def valide(lettres: str, mot: str) -> bool:
    for a in mot:
        if a not in lettres:
            return False
        else:
            lettres = lettres.replace(a, "", 1)
    return True

def getPos(l: str) -> int:
    return Alpha.find(l)

def score(mot: str, points: str) -> int:
    s = 0
    for m in mot:
        s += int(points[getPos(m)])
    return s

def ordi(lettres: str, Mots: str, Points: str) -> str:
    sc = 0
    better = ""
    for mot in Mots.split(" "):
        if valide(lettres, mot):
            if score(mot, Points) > sc:
                better = mot
    return better 

def verif(motOrdi: str, lettres: str, prop: str) -> bool:
    g = False
    c = ""
    for p in prop:
        if p in motOrdi:
            if c != p and g:
                return False
            g = True
    return g and valide(lettres, prop)

# on affiche un petit header pour que ce soit plus jolie
print("#####################")
print("     Blabla")
print(" Par William Hergès")
print("#####################")

pointsOrdi = 0
pointsPlayer = 0
pp = Pioche

while len(Pioche) > 0:
    print("\n------------------------------------------\n")

    letters, pp = tirage(pp, 4)
    print("Lettres de l'ordinateur :", letters)
    mOrd = ordi(letters, Mots, Points)
    sc = score(mOrd, Points)
    pointsOrdi += sc
    print(f"Mot de l'ordinateur : {mOrd} ({sc})\n")

    word = input("Votre proposition\n-> ").upper()
    if len(word) == 0:
        print("Pas de proposition.")
    elif len(word) > 5:
        print("Mot trop long")
    elif not verif(mOrd, Pioche, word):
        print(f"Le mot {word} est invalide")
    else:
        sco = score(word, Points)
        pointsPlayer += sco
        print(f"Le mot {word} vous rapporte {sco} points !")

print("\n------------------------------------------\n")

if pointsOrdi > pointsPlayer :
    print(f"Vous avez perdu ! ({pointsPlayer} contre {pointsOrdi})")
elif pointsOrdi == pointsPlayer:
    print(f"Égalité avec {pointsPlayer} !")
else:
    print(f"Vous avez gagné ! ({pointsPlayer} contre {pointsOrdi})")

